### ISSUE TITLE
Solver for the guards

### ISSUE THREAD

**Issue by a66as** [a66as/StateBasedTestCaseGeneration#8]
Now, in the generated tests, we ask (in generated comments) to satisfy the guards. This needs automation may be a SAT solver? We assume that the variables used within the guards' text are available in the class, and then all we need is to solve the inequalities/equalities.

**Comment by a66as** [comment]
May be it is possible without solvers.

**Comment by mhwaqas7232** [comment]
used regex based solver utils/ConditionParser.java
