### ISSUE TITLE
Dockrized web version for teaching state-based testing 

### ISSUE THREAD

**Issue by a66as** [a66as/StateBasedTestCaseGeneration#9]
The application should be converted to a web-based application and dockerized. The idea is that the web application contains the following:
1) A page motivating state-based testing
2) SUT page displaying editable files for the SUT
3) Unit Tests: A page displaying an empty unit test suite that the students can write an execute test on
4) Modeling: A page displaying the SUT state machine
5) Test Generation: A page for generating, editing, and executing all round trip paths tests and sneak paths tests
5) Evaluation: A page that injects (state-level) mutants to the SUT and calculates mutation kill score for the unit tests and the generated tests.

**Comment by mhwaqas7232** [comment]
fixed
